### ISSUE TITLE
Use the new Framework API?

### ISSUE THREAD

**Issue by jonniebigodes** [JohnAlbin/storybook-addon-fetch-mock#10]
Hey @JohnAlbin!
I'm one of the Storybook maintainers. I focus primarily on documentation and community outreach. I'm opening up this issue and letting you know that the Storybook API for building addons is currently being updated to factor in the changes introduced by the upcoming 7.0 release. If you're interested in making the required changes to help the community from benefiting from using your addon, we've prepared an abridged guide for the required changes [here](https://chromatic-ui.notion.site/Addon-migration-for-Storybook-7-002f2f627c1d470298ca94894ab8a040), and if you have any questions or issues, please reach out to us in the #prerelease channel in our [Discord Server](https://discord.gg/storybook). 

Hope you have a great day!

Stay safe

**Comment by jbogheand** [comment]
I am already getting this warning:

`WARN You (or an addon) are using the 'config' preset field. This has been replaced by 'previewAnnotations' and will be removed in 8.0`

Storybook 7.0.11 for vue3-vite

**Comment by JohnAlbin** [comment]
I've released a 2.0.0-beta.1 for testing.

I haven't had a chance to fully test this API upgrade so I would appreciate if anyone could test it out and report back.

https://www.npmjs.com/package/storybook-addon-fetch-mock

**Comment by NeilujD** [comment]
Hi !
I am encountering this issue:
```
[vite] Pre-transform error: No known conditions for "./preview" specifier in "storybook-addon-fetch-mock" package
```

Using 
* Storybook - 7.6.7
* Vite - 5.0.4

**Comment by JohnAlbin** [comment]
v2.0.0 has been released supporting v7 and v8 of Storybook.

https://www.npmjs.com/package/storybook-addon-fetch-mock
