### ISSUE TITLE
Does anyone maintain this project?

### ISSUE THREAD

**Issue by lrozewicz** [JohnAlbin/storybook-addon-fetch-mock#13]
Does anyone maintain this project? I posted a 3 week code fix (pull request), I would appreciate it if someone would take a look at it and possibly do a merge to the main branch.

https://github.com/JohnAlbin/storybook-addon-fetch-mock/pull/12

**Comment by JohnAlbin** [comment]
I'm more than happy to answer any of your questions.

> Does anyone maintain this project?

Yes.
