### ISSUE TITLE
You (or an addon) are using the 'config' preset field. This has been replaced by 'previewAnnotations' and will be removed in 8.0

### ISSUE THREAD

**Issue by jbogheand** [JohnAlbin/storybook-addon-fetch-mock#17]
Have been receiving this warning since updating to storybook 7

`You (or an addon) are using the 'config' preset field. This has been replaced by 'previewAnnotations' and will be removed in 8.0`

There is an ongoing conversation here https://github.com/storybookjs/storybook/issues/20529

**Comment by JohnAlbin** [comment]
This has been fixed with v2.0.0 which was just released.

https://www.npmjs.com/package/storybook-addon-fetch-mock
