### ISSUE TITLE
fetch-mock: Each route must define a response

### ISSUE THREAD

**Issue by sirganya** [JohnAlbin/storybook-addon-fetch-mock#8]
I'm getting this error trying to set up the package. 

`fetch-mock: Each route must define a response`

The app makes other calls to the backend cos I'm using Recoil and there are some dependencies. Do I have to catch them all?

I was wondering what the error might mean?  

```typescript
export default {
  title: "Example/Paragraph",
  component: Paragraph,
  decorators: [(storyFn) => <RecoilRoot initializeState={initState}>{storyFn()}</RecoilRoot>],
  parameters: {
    fetchMock: {
      mocks: [
        {
          name: "!",
          matcher: {
            url: "http://localhost:6006/gql-view-stack",
            method: "POST",
            headers: { "Content-Type": "application/json" },
          },

          reponse: {
            status: 200,
            body: { hello: "is it me you're looking for" },
          },
        },
      ],
    },
  },
  // More on argTypes: https://storybook.js.org/docs/react/api/argtypes
} as Meta<typeof Paragraph>;
```

**Comment by JohnAlbin** [comment]
I make this typo all the time.

Change "reponse" to "response". :)

**Comment by sirganya** [comment]
(Facepalm) That's embarrassing. I've become completely dependent on typescript... 

Thanks for getting back

**Comment by JohnAlbin** [comment]
https://github.com/JohnAlbin/storybook-addon-fetch-mock/pull/9

SEE! I told you I make that typo all the time. Doh.

Sorry about that.

**Comment by sirganya** [comment]
Hoist by your own petard. :)
